### PR TITLE
Merged updates from ash-nazg

### PR DESCRIPTION
**Pull request by brettz9**
I've made some updates/additions to eslint-config-ash-nazg and this merges them into eslint-config-passport-next

FWIW, the conflicts I had to resolve:

1. I did not apply my changes to CHANGES on passport-next's CHANGES at all.
2. For `great-eye`, `node`, `sauron-node`, and `sauron`, I switched to relative paths which is needed by eslint 6 to which I updated (and should also nicely help avoid merge conflicts in this regard in the future as well since such relative paths work fine with either repo).
3. `package.json` (and `package-lock.json`): I kept passport-next's different name/version/description and `test` of course, while updating the dependencies and some other scripts which can be used to build files which show the config's differences with the configs/plugins it inherits.

### CODE REVIEW

**Comment by brettz9** [comment]
Apologies, I need to hold off on this, until one more dependency may be updated.

**Comment by rwky** [comment]
I'll check this out next week, I'm away for a few days

**Comment by rwky** [comment]
@brettz9 I've taken a look at this and run it against the current passport-next/passport master it only throws a few errors relating to jsdoc which we can fix in passport-next/passport

How close to completion is this?

**Comment by brettz9** [comment]
I have one fix for a dependency that would be nice to add and I hope to finish that today...

**Comment by brettz9** [comment]
Ok, I have added the updates I wanted to include.

**Pull request merged**
